app = "projeto01-2023-site-php-oop-seusucesso"

primary_region = "gru"

[build]
  dockerfile = "Dockerfile"  # Caminho do Dockerfile

[[services]]
  internal_port = 3000  # A porta exposta pela aplicação no Docker
  processes = ["app"]

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443
